### ISSUE TITLE
May I have a look at your code?

### ISSUE THREAD

**Issue by Y-J-Q-L** [lanqz7766/GKD#1]
Hello, excuse me, I am very interested in your work, which is of great research value, but I have encountered some problems when replicating the code, may I have a look at your code?

**Comment by lanqz7766** [comment]
Hi, I just uploaded our code, hope it helps!

**Comment by Jocelyn-Jiaxin** [comment]
Thank you very much, your work is very meaningful to me, and I look forward to your future fruitful achievements
