### ISSUE TITLE
想请教下您，具体的coco-traffic数据集如何获取，我下载了coco2017数据集，这个filter_traffic.py执行命令是什么呢？

### ISSUE THREAD

**Issue by chaoaibeidanci** [lanqz7766/GKD#3]

**Comment by lanqz7766** [comment]
你好，你可以看到main() 函数内的参数只有3个，--input_json file (目前GT label 的json file path), --output_json (输出新annotation的path), 以及--categories 你需要的类别，在文章中我们提到的是三个类别，具体你可以参考filter_traffic内部的详细code
