### ISSUE TITLE
environment setup issue 

### ISSUE THREAD

**Issue by nandini211995** [lanqz7766/GKD#4]
Dear authors,

I am reproducing the shared code. I need the details for setup environment such as pytorch version, cuda version etc. 
And checkpoint file is missing : "/users/PCS0252/lanqz7766/MMdetection/checkpoints/coco/faster_rcnn_r101_fpn_2x_coco/epoch_24.pth"
Kindly share these details.

**Comment by lanqz7766** [comment]
Hi,

Regarding the PyTorch and CUDA versions, I used PyTorch 1.13 and CUDA 11.7.1. However, it may not be necessary to match these exact versions for running the code. For more details, you can refer to the MMDetection documentation: https://mmdetection.readthedocs.io/en/v2.25.0/.

For the COCO checkpoint, you can download it from the following link: https://github.com/open-mmlab/mmdetection/tree/main/configs/faster_rcnn.

As for the KITTI dataset, I recommend downloading the dataset and training your model, as it is relatively small. This will help you get the best results tailored to your specific requirements.
